/* ============================================================================
 *  Turning a request body into something safe to store.
 *
 *  The rule this file exists to enforce: nothing reaches the database that was
 *  not explicitly copied across, coerced to the right type and cut to length. A
 *  request body is a suggestion, not data.
 *
 *  Everything here is a pure function, so the rules can be read top to bottom
 *  without knowing anything about Express or Mongo.
 * ========================================================================== */

import { QUESTION_TYPES, VERDICTS } from '../models/Attempt.js';

const MAX_ANSWERS = 40;
const MAX_TELLS = 8;
const MAX_DURATION_MS = 6 * 60 * 60 * 1000; // 6 hours; anything longer is junk

/** Trim to a string of at most `max` characters, or null if there is nothing. */
function text(value, max) {
  if (typeof value !== 'string') return null;
  /* Strip control characters: they serve no purpose here and make logs and
   * terminals misbehave when the data is read back. */
  const cleaned = value.replace(/[\u0000-\u001f\u007f]/g, ' ').trim();
  return cleaned === '' ? null : cleaned.slice(0, max);
}

function number(value, { min, max, fallback = null }) {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

function integer(value, { min, max, fallback = 0 }) {
  const n = number(value, { min, max, fallback });
  return n === null ? fallback : Math.trunc(n);
}

function boolean(value) {
  return value === true;
}

/** Round to 3 decimals so stored scores match what the site displays. */
function score(value, { min = 0, max = 1 } = {}) {
  const n = number(value, { min, max, fallback: null });
  return n === null ? null : Math.round(n * 1000) / 1000;
}

/** Session ids are generated by us, so anything outside this shape is not ours. */
function sessionId(value) {
  const raw = text(value, 64);
  if (!raw) return null;
  return /^[A-Za-z0-9_-]{8,64}$/.test(raw) ? raw : null;
}

function sanitizeAnswer(input) {
  if (!input || typeof input !== 'object') return null;

  const questionId = text(input.questionId, 64);
  if (!questionId) return null; // an answer with no question is not worth keeping

  const optionId = text(input.optionId, 32);
  const answerText = text(input.text, 1000);

  /* Every answer is either a picked option or something typed. A row with
   * neither records that a question existed and nothing else, which the site
   * cannot produce — so it is malformed input, and storing it would leave holes
   * in the data that look like real answers. */
  if (!optionId && !answerText) return null;

  const type = QUESTION_TYPES.includes(input.type) ? input.type : 'other';

  return {
    questionId,
    type,
    prompt: text(input.prompt, 300) ?? '',
    optionId,
    optionLabel: text(input.optionLabel, 240),
    text: answerText,
    /* Tri-state: true, false, or "this question is not scored". */
    correct: typeof input.correct === 'boolean' ? input.correct : null,
    elapsedMs: integer(input.elapsedMs, { min: 0, max: MAX_DURATION_MS }),
    changes: integer(input.changes, { min: 0, max: 50 }),
  };
}

/**
 * Validate and normalise an incoming attempt.
 *
 * @returns {{ok: true, value: object} | {ok: false, error: string}}
 */
export function sanitizeAttempt(body) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return { ok: false, error: 'body must be an object' };
  }

  /* The verdict is the one field with no sensible default: without it there is
   * nothing to record. */
  if (!VERDICTS.includes(body.verdict)) {
    return { ok: false, error: `verdict must be one of: ${VERDICTS.join(', ')}` };
  }

  const confidence = score(body.confidence);
  if (confidence === null) {
    return { ok: false, error: 'confidence must be a number between 0 and 1' };
  }

  const answers = Array.isArray(body.answers)
    ? body.answers.slice(0, MAX_ANSWERS).map(sanitizeAnswer).filter(Boolean)
    : [];

  const tells = Array.isArray(body.tells)
    ? body.tells
        .slice(0, MAX_TELLS)
        .map((tell) => text(tell, 240))
        .filter(Boolean)
    : [];

  const client = body.client && typeof body.client === 'object' ? body.client : {};

  return {
    ok: true,
    value: {
      sessionId: sessionId(body.sessionId),
      verdict: body.verdict,
      confidence,
      knowledge: score(body.knowledge),
      behaviour: score(body.behaviour, { min: -1, max: 1 }),
      tells,
      tiebreakUsed: boolean(body.tiebreakUsed),
      knownReturner: boolean(body.knownReturner),
      durationMs: integer(body.durationMs, { min: 0, max: MAX_DURATION_MS }),
      answers,
      client: {
        /* userAgent is filled in from the request header by the route, not from
         * the body, so it cannot be spoofed by whatever posted this. */
        userAgent: null,
        language: text(client.language, 32),
        timezone: text(client.timezone, 64),
        screen: /^\d{1,5}x\d{1,5}$/.test(String(client.screen ?? '')) ? String(client.screen) : null,
      },
    },
  };
}
